import { RandomEvent } from "./randomEventType";


export const randomEvents: RandomEvent[] = [
    {
      id: 1,
      title: "Unexpected Medical Expense",
      description: "You had to visit the emergency room for a minor injury.",
      financialImpact: -300,
      impactType: "savings",
      probability: 0.1,
    },
    {
      id: 2,
      title: "Birthday Gift",
      description: "A relative sent you money for your birthday!",
      financialImpact: 100,
      impactType: "savings",
      probability: 0.15,
    },
    {
      id: 3,
      title: "Car Repair",
      description: "Your car broke down and needed urgent repairs.",
      financialImpact: -250,
      impactType: "savings",
      probability: 0.08,
    },
    {
      id: 4,
      title: "Tax Refund",
      description: "You received an unexpected tax refund!",
      financialImpact: 200,
      impactType: "savings",
      probability: 0.05,
    },
    {
      id: 5,
      title: "Laptop Replacement",
      description: "Your laptop stopped working and you need a new one for classes.",
      financialImpact: -600,
      impactType: "savings",
      probability: 0.03,
    },
    {
      id: 6,
      title: "Part-time Job Opportunity",
      description: "You found a weekend job that pays extra savings.",
      financialImpact: 250,
      impactType: "savings",
      probability: 0.07,
    },
    {
      id: 7,
      title: "Scholarship Award",
      description: "You received a small scholarship for academic excellence!",
      financialImpact: 500,
      impactType: "savings",
      probability: 0.04,
    },
    {
      id: 8,
      title: "Utility Bill Spike",
      description: "This month's utility bills were much higher than expected.",
      financialImpact: -120,
      impactType: "savings",
      probability: 0.12,
    },
    {
      id: 9,
      title: "Party Night with Friends",
      description: "You went out for a fun night with friends and spent more than planned.",
      financialImpact: -60,
      impactType: "savings",
      probability: 0.1,
    },
    {
      id: 10,
      title: "Phone Damage",
      description: "You dropped your phone and need to pay for repairs.",
      financialImpact: -150,
      impactType: "savings",
      probability: 0.09,
    },
    {
      id: 11,
      title: "Tutoring Opportunity",
      description: "A classmate asked you to tutor them for the semester.",
      financialImpact: 180,
      impactType: "savings",
      probability: 0.06,
    },
    {
      id: 12,
      title: "Unexpected Textbook Costs",
      description: "Your professor required an additional textbook mid-semester.",
      financialImpact: -85,
      impactType: "savings",
      probability: 0.11,
    },
    {
      id: 13,
      title: "Weekend Trip to Hawaii",
      description: "You found an amazing last-minute deal on a weekend getaway to Hawaii!",
      financialImpact: -450,
      impactType: "savings",
      probability: 0.04,
    },
    {
      id: 14,
      title: "Contest Winner",
      description: "You won a small prize in a campus contest!",
      financialImpact: 75,
      impactType: "savings",
      probability: 0.08,
    },
    {
      id: 15,
      title: "Roommate Broke Apartment TV",
      description: "Your roommate accidentally broke the shared TV and you need to split the cost of a replacement.",
      financialImpact: -150,
      impactType: "savings",
      probability: 0.05,
    },
  ];